version: '1'
services:
  websrvr:
    image: nginx
    ports:
      - "3838:3838"
    depends_on:
      - archaeodash
      - archaeodashbeta
      - dataentry
      - boxes
    volumes:
      - "./websrvr/docker:/var/www/html"
      - "./websrvr/docker/conf:/usr/local/nginx/conf"
    working_dir: "/usr/local/nginx/conf"
    restart: unless-stopped

  archaeodash:
    build: Archaeodash/docker
    ports:
      - "13838:3838"
    restart: unless-stopped
    user: "root"
    volumes:
      - "./Archaeodash:/srv/shiny-server/"
    working_dir: "/srv/shiny-server"

  archaeodashbeta:
    build: Archaeodashbeta/docker
    ports:
      - "23838:3838"
    restart: unless-stopped
    user: "root"
    volumes:
      - "./Archaeodashbeta:/srv/shiny-server/"
    working_dir:  "/srv/shiny-server"

  dataentry:
    build: ShinyDataEntry/docker
    ports:
      - "33838:3838"
    restart: unless-stopped
    user: "root"
    volumes:
      - "./ShinyDataEntry:/srv/shiny-server/"
    working_dir:  "/srv/shiny-server"

  boxes:
    build: CAScontainerUpdater/docker
    ports:
      - "43838:3838"
    restart: unless-stopped
    user: "root"
    volumes:
      - "./CAScontainerUpdater:/srv/shiny-server/"
    working_dir:  "/srv/shiny-server"

volumes:
  Archaeodash:  
  Archaeodashbeta:
  websrvr:
  ShinyDataEntry:
  CAScontainerUpdater:
networks:
  privatenet:
